In [6]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

import matplotlib.pyplot as plt

In [7]:
from scipy import sparse

In [8]:
X_train = sparse.load_npz(
    "../../artifacts/X_train_tree.npz"
)

X_test = sparse.load_npz(
    "../../artifacts/X_test_tree.npz"
)

In [9]:
import pandas as pd

In [10]:
y_train = pd.read_csv(
    "../../artifacts/y_train.csv"
)

y_test = pd.read_csv(
    "../../artifacts/y_test.csv"
)

In [11]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)

print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (81780, 5000)
X_test: (20554, 5000)
y_train: (81780, 1)
y_test: (20554, 1)


In [12]:
y_train = y_train.squeeze()
y_test = y_test.squeeze()

In [13]:
print(y_train.shape)
print(y_test.shape)

(81780,)
(20554,)


In [14]:
print(y_train.value_counts())

SEVERITY
CLASS - 2    46270
CLASS - 1    32140
CLASS - 3     3370
Name: count, dtype: int64


In [15]:
from sklearn.ensemble import RandomForestClassifier


rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1
)

In [16]:
rf_model.fit(
    X_train,
    y_train
)

,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel. :meth:`fit`, :meth:`predict`,:meth:`decision_path` and :meth:`apply` are all parallelized over thetrees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`context. ``-1`` means using all processors. See :term:`Glossary<n_jobs>` for more details.",-1
,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"class_weight class_weight: {""balanced"", ""balanced_subsample""}, dict or list of dicts, default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one. Formulti-output problems, a list of dicts can be provided in the sameorder as the columns of y.Note that for multioutput (including multilabel) weights should bedefined for each class of every column in its own dict. For example,for four-class multilabel classification weights should be[{0: 1, 1: 1}, {0: 1, 1: 5}, {0: 1, 1: 1}, {0: 1, 1: 1}] instead of[{1:1}, {2:5}, {3:1}, {4:1}].The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``The ""balanced_subsample"" mode is the same as ""balanced"" except thatweights are computed based on the bootstrap sample for every treegrown.For multi-output, the weights of each column of y will be multiplied.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified.",'balanced'
,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_fe

In [17]:
y_pred = rf_model.predict(X_test)

In [18]:
y_prob = rf_model.predict_proba(X_test)

In [19]:
y_prob.shape

(20554, 3)

In [20]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [21]:
accuracy = accuracy_score(
    y_test,
    y_pred
)

print("Accuracy:", accuracy)

Accuracy: 0.8164834095553177


In [22]:
precision = precision_score(
    y_test,
    y_pred,
    average="weighted"
)

print("Precision:", precision)

Precision: 0.8235074347710981


In [23]:
recall = recall_score(
    y_test,
    y_pred,
    average="weighted"
)

print("Recall:", recall)

Recall: 0.8164834095553177


In [24]:
f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)

print("F1 Score:", f1)

F1 Score: 0.8168506146075878


In [25]:
print(
    classification_report(
        y_test,
        y_pred
    )
)

              precision    recall  f1-score   support

   CLASS - 1       0.77      0.88      0.82      8455
   CLASS - 2       0.88      0.78      0.83     11282
   CLASS - 3       0.65      0.68      0.66       817

    accuracy                           0.82     20554
   macro avg       0.77      0.78      0.77     20554
weighted avg       0.82      0.82      0.82     20554



In [26]:
cm = confusion_matrix(
    y_test,
    y_pred
)

print(cm)

[[7423 1022   10]
 [2189 8807  286]
 [  70  195  552]]


In [ ]:
import pandas as pd


feature_names = pd.read_csv(
    "../../artifacts/feature_names_tree.csv"
)


importance = pd.DataFrame({
    "Feature": feature_names.iloc[:,0],
    "Importance": rf_model.feature_importances_
})


importance = importance.sort_values(
    by="Importance",
    ascending=False
)


importance.head(20)

FileNotFoundError: [Errno 2] No such file or directory: '../artifacts/feature_names_tree.csv'

In [ ]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

In [ ]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [ ]:
cv_scores = cross_val_score(
    rf_model,
    X_train,
    y_train,
    cv=cv,
    scoring="f1_weighted",
    n_jobs=-1
)

In [ ]:
print("F1 Scores for each fold:")
print(cv_scores)

print("\nAverage F1 Score:")
print(cv_scores.mean())

print("\nStandard Deviation:")
print(cv_scores.std())

F1 Scores for each fold:
[0.84903182 0.84373541 0.84426175 0.85131889 0.85153162]

Average F1 Score:
0.8479758985253387

Standard Deviation:
0.0033677995566167066


In [ ]:
import numpy as np
import pandas as pd
from scipy import sparse

X_train = sparse.load_npz(
    "../../artifacts/X_train_tree.npz"
)

X_test = sparse.load_npz(
    "../../artifacts/X_test_tree.npz"
)

In [ ]:
print(type(X_train))
print(X_train.shape)

<class 'scipy.sparse._csr.csr_matrix'>
(81780, 5000)


In [ ]:
print("Shape:", X_train.shape)
print("Non-zero values:", X_train.nnz)
print("Total possible values:", X_train.shape[0] * X_train.shape[1])

Shape: (81780, 5000)
Non-zero values: 2939019
Total possible values: 408900000


In [ ]:
sparsity = 1 - (
    X_train.nnz / (X_train.shape[0] * X_train.shape[1])
)

print("Sparsity:", sparsity)

Sparsity: 0.9928123771093177


In [ ]:
sample = X_train[:5, :20].toarray()

print(sample)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
feature_names = pd.read_csv(
    "../artifacts/feature_names_tree.csv"
)

row = X_train[0]

non_zero_indices = row.indices
non_zero_values = row.data

row_df = pd.DataFrame({
    "Feature": feature_names.iloc[non_zero_indices, 0].values,
    "Value": non_zero_values
})

display(row_df)

,Feature,Value
0,text__AND REPLACE,0.151643
1,text__AT,0.079666
2,text__AT EXPOSURE,0.105495
3,text__AT TIME,0.077318
4,text__BUILDING,0.066491
5,text__BULGING,0.198189
6,text__CRACKED,0.153487
7,text__EXTERIOR,0.120954
8,text__FAILURE,0.061259
9,text__FAILURE TO,0.061431
